version: "3.7"
services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ".env"
    environment:
      - DB_HOST=postgres
  postgres:
    image: "postgres:10-alpine"
    env_file:
      - ".env"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
