version: "3.7"
services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ".env"
    environment:
      - DATABASE_URL=postgres://postgres:@postgres:5432/cms_development?sslmode=disable
  postgres:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cms_development
